# Copyright (c) 2023, Bennett Samowich <bennett@foolean.org>
# All rights reserved
# SPDX short identifier: BSD-3-Clause
---

# We put the entire role in a block so we can create
# a role specific tag, which saves the caller from
# having to do so in their playbook.
- name: Role foolean/cyrusimap
  block:

    - name: Ensure IMAP and POP3 server (Cyrus IMAP) is not installed (CIS)
      become: true
      ansible.builtin.package:
        name:
          - 'cyrus-imap'
        state: absent

  # Tags to be applied to this role (block)
  tags:
    - 'role_foolean_cyrusimap'
